# -*- coding: utf-8 -*-
"""DeepFashion 50 类英中对照（与 CategoryRepository.kt 一致）"""

EN_TO_ZH = {
    "Anorak": "冲锋衣",
    "Blazer": "西装外套",
    "Blouse": "女式衬衫",
    "Bomber": "飞行员夹克",
    "Button-Down": "纽扣衫",
    "Cardigan": "开衫",
    "Flannel": "法兰绒衬衫",
    "Halter": "挂脖上衣",
    "Henley": "半开领衫",
    "Hoodie": "连帽衫",
    "Jacket": "夹克",
    "Jersey": "运动衫",
    "Parka": "派克大衣",
    "Peacoat": "双排扣大衣",
    "Poncho": "斗篷",
    "Sweater": "毛衣",
    "Tank": "背心",
    "Tee": "T恤",
    "Top": "上衣",
    "Turtleneck": "高领衫",
    "Capris": "七分裤",
    "Chinos": "卡其裤",
    "Culottes": "阔腿短裤",
    "Cutoffs": "牛仔短裤",
    "Gauchos": "高乔裤",
    "Jeans": "牛仔裤",
    "Jeggings": "打底裤",
    "Jodhpurs": "马裤",
    "Joggers": "慢跑裤",
    "Leggings": "紧身裤",
    "Sarong": "纱笼",
    "Shorts": "短裤",
    "Skirt": "裙子",
    "Sweatpants": "运动裤",
    "Sweatshorts": "运动短裤",
    "Trunks": "泳裤",
    "Caftan": "长袍",
    "Cape": "斗篷",
    "Coat": "外套",
    "Coverup": "罩衫",
    "Dress": "连衣裙",
    "Jumpsuit": "连体衣",
    "Kaftan": "长袍",
    "Kimono": "和服",
    "Nightdress": "睡裙",
    "Onesie": "连体服",
    "Robe": "长袍",
    "Romper": "连体短裤",
    "Shirtdress": "衬衫裙",
    "Sundress": "太阳裙",
}

ENGLISH_NAMES = list(EN_TO_ZH.keys())
